---
# 设置文件和请求大小
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: true # 开启 multipart 懒加载
---
# 文件存储配置
dromara:
  x-file-storage:
    default-platform: minio-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    minio: # MinIO，由于 MinIO SDK 支持 AWS S3，其它兼容 AWS S3 协议的存储平台也都可配置在这里
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: admin
        secret-key: Admin@123
        end-point: "http://dev.minio.lingo.local"
        bucket-name: test
        domain: "http://dev.minio.lingo.local/test/" # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: ateng/ # 基础路径
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: xxx
        secret-key: xxx
        end-point: oss-cn-chengdu.aliyuncs.com
        bucket-name: lingo-bucket-data
        domain: https://lingo-bucket-data.oss-cn-chengdu.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: ateng/ # 基础路径
    ftp:
      - platform: ftp-1 # 存储平台标识
        enable-storage: true  # 启用存储
        host: 192.168.1.13 # 主机，例如：192.168.1.105
        port: 21 # 端口，默认21
        user: admin # 用户名，默认 anonymous（匿名）
        password: "Admin@123" # 密码，默认空
        domain: ftp://192.168.1.13/data/ # 访问域名，注意“/”结尾，例如：ftp://192.168.1.105/
        base-path: ateng/ # 基础路径
        storage-path: /data/ # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”