server:
  port: 11017
spring:
  application:
    name: ${project.artifactId}
logging:
  level:
    root: info
    io.github.atengk: debug
---
sshj:
  host: 192.168.1.10
  port: 38101
  username: root
  password: Admin@123
  connect-timeout: 5000
  kex-timeout: 10000
  heartbeat-interval: 30
  pool-size: 8
  strict-host-key-checking: false
  #known-hosts-path: ~/.ssh/known_hosts
  known-hosts-path: ""
