---
# Spring Cloud Stream Kafka 配置
spring:
  cloud:
    stream:
      default:
        binder: kafka-default
        group: ateng-${spring.application.name:-0}-${spring.profiles.active:-0}
        content-type: application/json
      binders:
        kafka-default:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: 192.168.1.10:9094
            spring.cloud.stream.kafka.binder.producer-properties:
              max.request.size: 10485760
            spring.cloud.stream.kafka.binder.consumer-properties:
              fetch.max.bytes: 10485760
              auto.offset.reset: earliest
