server:
  port: 14002
  servlet:
    context-path: /
spring:
  main:
    web-application-type: servlet
  application:
    name: ${project.artifactId}
---
# 设置文件和请求大小
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
---
# S3 配置
s3:
  endpoint: http://192.168.1.12:20006
  access-key: admin
  secret-key: Admin@123
  region: us-east-1
  bucket-name: data
  path-style-access: true
