server:
  port: 11015
spring:
  application:
    name: ${project.artifactId}
  grpc:
    server:
      port: 21015
---
# gRPC 客户端配置
spring:
  grpc:
    client:
      channels:
        greeter:
          address: localhost:21015
          negotiation-type: plaintext
