server:
  port: 16031
  servlet:
    context-path: /
spring:
  main:
    web-application-type: servlet
  application:
    name: ${project.artifactId}
---
# Zookeeper 配置
zookeeper:
  connect-string: 192.168.1.10:44276
  session-timeout: 60000
  connection-timeout: 15000
