---
# Mybatis Flex的配置 https://mybatis-flex.com/zh/base/configuration.html
mybatis-flex:
  global-config:
    print-banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
spring:
  # 数据库的相关配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ateng
    #url: jdbc:postgresql://127.0.0.1:5672/ateng?currentSchema=public&stringtype=unspecified
    username: postgres  # 数据库用户名
    password: Lingo@local_postgresql_5432  # 数据库密码
    driver-class-name: org.postgresql.Driver  # PostgreSQL数据库驱动类
    # driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL数据库驱动类
    type: com.alibaba.druid.pool.DruidDataSource  # 使用Druid数据源
    # Druid连接池配置 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      initial-size: 10  # 初始化连接池大小
      min-idle: 10  # 最小空闲连接数
      max-active: 1000  # 最大活跃连接数
      max-wait: 10000  # 获取连接的最大等待时间，单位毫秒
    # type: com.zaxxer.hikari.HikariDataSource  # 使用 HikariCP 数据源
    # hikari:
    #   maximum-pool-size: 1000  # 最大连接池大小
    #   minimum-idle: 10  # 最小空闲连接数
    #   idle-timeout: 30000  # 空闲连接超时时间，单位毫秒
    #   connection-timeout: 30000  # 获取连接的最大等待时间，单位毫秒