---
# Spring Cloud Stream RabbitMQ 配置
spring:
  cloud:
    stream:
      default:
        binder: rabbit-default
        group: ateng-${spring.application.name:-0}-${spring.profiles.active:-0}
        content-type: application/json
      binders:
        rabbit-default:
          type: rabbit
          environment:
            spring.rabbitmq.addresses: 192.168.1.10:29210
            spring.rabbitmq.username: admin
            spring.rabbitmq.password: Admin@123
            spring.rabbitmq.virtual-host: /
