server:
  port: 12001
  servlet:
    context-path: /
spring:
  main:
    web-application-type: servlet
  application:
    name: ${project.artifactId}
---
# Sa-Token 配置
sa-token:
  token-name: satoken # token 名称（同时也是 cookie 名称）
  timeout: 86400 # token 有效期（单位：秒），默认30天，-1 代表永久有效
  active-timeout: -1 # token 最低活跃频率（单位：秒），超时未访问会被冻结，-1代表永不冻结
  is-concurrent: true # 是否允许同一账号多地同时登录，true 为允许，false 为新登录挤掉旧登录
  is-share: true # 是否共用一个 token，true 为共享，false 为每次登录新建 token
  token-style: uuid # token 风格（可选：uuid、simple-uuid、random-32、random-64、random-128、tik）
  is-log: false # 是否输出操作日志
  is-print: false # 是否打印logo
  alone-redis:
    database: 91 # Redis 数据库索引（默认为0）
    host: 192.168.1.10 # Redis 服务器地址
    port: 42784 # Redis 服务器连接端口
    password: Admin@123 # Redis 服务器连接密码（默认为空）
    timeout: 10s # 连接超时时间
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（负值表示无连接数限制）
        max-wait: -1s # 连接池最大阻塞等待时间（负值表示无限制）
        max-idle: 100 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        time-between-eviction-runs: 1s # 空闲对象逐出器线程的运行间隔时间
  sign:
    secret-key: yN7IRdIJm84mOMiJ65KX372fbDl9cRJN # API 接口签名秘钥 （随便乱摁几个字母即可）
    timestamp-disparity: 900000 # 接口调用时的时间戳允许的差距（单位：ms），-1 代表不校验差距，默认15分钟
---
# 数据库的相关配置
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.10:32297/ateng_satoken?currentSchema=public&stringtype=unspecified  # PostgreSQL数据库连接URL
    username: postgres  # 数据库用户名
    password: Lingo@local_postgresql_5432  # 数据库密码
    # driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类，框架会自动适配
    type: com.zaxxer.hikari.HikariDataSource  # 使用 HikariCP 数据源
    hikari:
      maximum-pool-size: 1000  # 最大连接池大小
      minimum-idle: 10  # 最小空闲连接数
      idle-timeout: 30000  # 空闲连接超时时间，单位毫秒
      connection-timeout: 30000  # 获取连接的最大等待时间，单位毫秒
# Mybatis Flex的配置 https://mybatis-flex.com/zh/base/configuration.html
mybatis-flex:
  global-config:
    print-banner: false
