server:
  port: 15001
  servlet:
    context-path: /
spring:
  main:
    web-application-type: servlet
  application:
    name: ${project.artifactId}
---
# 数据库的相关配置
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.10:35725/kongyu  # MySQL数据库连接URL
#    #url: jdbc:postgresql://192.168.1.10:32297/kongyu?currentSchema=public&stringtype=unspecified  # PostgreSQL数据库连接URL
#    username: root  # 数据库用户名
#    password: Admin@123  # 数据库密码
#    # driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类，框架会自动适配
#    type: com.alibaba.druid.pool.DruidDataSource  # 使用Druid数据源
#    # Druid连接池配置 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
#    druid:
#      initial-size: 10  # 初始化连接池大小
#      min-idle: 10  # 最小空闲连接数
#      max-active: 1000  # 最大活跃连接数
#      max-wait: 10000  # 获取连接的最大等待时间，单位毫秒
#      async-init: true
# Mybatis Flex的配置 https://mybatis-flex.com/zh/base/configuration.html
mybatis-flex:
  global-config:
    print-banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  datasource:
    # 第一个数据源为默认数据源
    # https://mybatis-flex.com/zh/core/multi-datasource.html
    mysql:
      url: jdbc:mysql://192.168.1.10:35725/kongyu
      username: root
      password: Admin@123
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 10
      min-idle: 10
      max-active: 1000
      max-wait: 10000
      async-init: true
    doris:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.12:9030/kongyu
      username: admin
      password: Admin@123
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 10000
    doris-arrow-flight:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.apache.arrow.driver.jdbc.ArrowFlightJdbcDriver
      url: jdbc:arrow-flight-sql://192.168.1.18:9031?useServerPrepStmts=false&cachePrepStmts=true&useSSL=false&useEncryption=false
      username: admin
      password: Admin@123
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 10000
