info:
  atengApp:
    title: prod
    group: ${project.groupId}
    artifactId: ${project.artifactId}
    name: ${project.name}
    version: ${project.version}
    description: ${project.description}
